---
abstract: 'Test DNS queries and zone configuration'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
generated_by: 'Module::Build version 0.3513'
keywords:
  - DNS
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-DNS
provides:
  Test::DNS:
    file: lib/Test/DNS.pm
    version: 0.05
requires:
  Moose: 0.8
  Net::DNS: 0.65
  Set::Object: 0
  Test::Builder: 0
  Test::Deep: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/xsawyerx/test-dns
version: 0.05
